name: Auto Update QA Branch

on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sleep for 24 hours
      run: sleep 86400  # Sleep for 24 hours (24 * 60 * 60 seconds)

    - name: Switch to QA branch, pull changes from main
      run: |
        git checkout qa-branch
        git pull origin main
        git push origin qa-branch


