name: Main to QA Branch

on:
  schedule:
    - cron: '30 6 * * *'  # This will trigger the workflow every day at 12:00 pm IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 0
    - name: Build project
      run: |
        # Add your build commands here
        # For example, if it's a Node.js project:
        npm install
        npm run build
      continue-on-error: true  # Continue to the next step even if the build fails
    - name: Push changes
      if: success()  # Only push if the build was successful
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: qa-branch
